name: Run Flask App
on: [push]

jobs:
  run-app:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          python -m pip install flask
      
      - name: Run Flask app
        run: |
          cd flaskapp
          python some_app.py
